"""add flag to nodes

Revision ID: 8777af9796e7
Revises: 973dc5c8ac37
Create Date: 2026-03-18 10:54:46.027258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8777af9796e7'
down_revision: Union[str, Sequence[str], None] = '973dc5c8ac37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('flag', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'flag')
    # ### end Alembic commands ###
