"""add nodes and proxies tables

Revision ID: 973dc5c8ac37
Revises: 5c8c0fdc6299
Create Date: 2026-03-18 10:45:57.932647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973dc5c8ac37'
down_revision: Union[str, Sequence[str], None] = '5c8c0fdc6299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('host', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_panel_id'), 'nodes', ['panel_id'], unique=True)
    op.create_table('proxies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('mtg_username', sa.String(length=128), nullable=False),
    sa.Column('link', sa.String(length=512), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('traffic_limit_gb', sa.Double(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxies_mtg_username'), 'proxies', ['mtg_username'], unique=False)
    op.create_index(op.f('ix_proxies_node_id'), 'proxies', ['node_id'], unique=False)
    op.create_index(op.f('ix_proxies_user_id'), 'proxies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proxies_user_id'), table_name='proxies')
    op.drop_index(op.f('ix_proxies_node_id'), table_name='proxies')
    op.drop_index(op.f('ix_proxies_mtg_username'), table_name='proxies')
    op.drop_table('proxies')
    op.drop_index(op.f('ix_nodes_panel_id'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
